export enum StringList {
  MAIN_TITLE = 'Semantic Switch',
  MAIN_SUBTITLE = 'Network Software for Semantic Ontology',
  HOME_COPY1 = 'An application service providing knowledge management.',
  HOME_COPY2 = 'Data-driven maps of business entity relationships.',
  FOOTER_COPYRIGHT = '©2023 WL Solutions LLC. All Rights Reserved.',
  FOOTER_TRADEMARK = 'Smart Narrative is a registered trademark.',
  MOBILE_FOOTER_COPYRIGHT_ONE = '©2023 WL Solutions LLC.',
  MOBILE_FOOTER_COPYRIGHT_TWO = 'All Rights Reserved.',
  MOBILE_FOOTER_TRADEMARK = 'Smart Narrative is a registered trademark.',
  NETWORK_IMAGE = 'https://smartnarrative.network/images/network.jpg',
  HOME_LINK = '/',
  ONTOLOGY_LINK = '/ontology',
  SWITCH_LINK = '/switch',
  PRICING_LINK = '/pricing',
  ONTOLOGY_LABEL = 'ONTOLOGY',
  ONTOLOGY_1 = 'An ontology represents a set of concepts, and the relationships between those concepts. It specifies the types of things that can exist, and the relationships between those things.',
  ONTOLOGY_2 = 'Semantic ontology is concerned with the meaning of concepts, and how these meanings can be used for enterprise knowledge management.',
  SWITCH_1 = 'A semantic switch creates a network of entities related by organizational concepts.',
  SWITCH_2 = 'The relationships are mapped by data flowing from the entities.',
  SWITCH_LABEL = 'SWITCH',
  PRICING_LABEL = 'PRICING',
  PRICING_PRODUCT_LABEL_1 = 'STARTER',
  PRICING_PRODUCT_LABEL_2 = 'ENTERPRISE',
  PRICING_PRODUCT_LABEL_3 = 'CUSTOM',
  PRICING_COPY_1 = 'Choose from one of three service options: ',
}
