export enum StringList {
  MAIN_TITLE = 'Semantic Switch',
  MAIN_SUBTITLE = 'Network Software for Semantic Ontology',
  FOOTER_COPYRIGHT = '©2023 WL Solutions LLC. All Rights Reserved.',
  FOOTER_TRADEMARK = 'Smart Narrative is a registered trademark.',
  MOBILE_FOOTER_COPYRIGHT_ONE = '©2023 WL Solutions LLC.',
  MOBILE_FOOTER_COPYRIGHT_TWO = 'All Rights Reserved.',
  MOBILE_FOOTER_TRADEMARK = 'Smart Narrative is a registered trademark.',
  NETWORK_IMAGE = 'https://smartnarrative.network/images/network.jpg',
  HOME_LINK = '/',
  ONTOLOGY_LINK = '/ontology',
  SWITCH_LINK = '/switch',
  PRICING_LINK = '/pricing',
  SEMANTIC_ONTOLOGY_1 = 'An ontology represents a set of concepts, and the relationships between those concepts. It specifies the types of things that can exist, and the relationships between those things.',
  SEMANTIC_ONTOLOGY_2 = 'Semantic ontology is concerned with the meaning of concepts, and how these meanings can be represented in a way that facilitates computer processing.',
}
